// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currencypb/currency.proto

package currencypb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Currency struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HighestPriceDate     string   `protobuf:"bytes,2,opt,name=highest_price_date,json=highestPriceDate,proto3" json:"highest_price_date,omitempty"`
	HighestPrice         string   `protobuf:"bytes,3,opt,name=highest_price,json=highestPrice,proto3" json:"highest_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_a78bbd6cac4864d8, []int{0}
}

func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (m *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(m, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetHighestPriceDate() string {
	if m != nil {
		return m.HighestPriceDate
	}
	return ""
}

func (m *Currency) GetHighestPrice() string {
	if m != nil {
		return m.HighestPrice
	}
	return ""
}

func init() {
	proto.RegisterType((*Currency)(nil), "currency.Currency")
}

func init() { proto.RegisterFile("currencypb/currency.proto", fileDescriptor_a78bbd6cac4864d8) }

var fileDescriptor_a78bbd6cac4864d8 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x2e, 0x2d, 0x2a,
	0x4a, 0xcd, 0x4b, 0xae, 0x2c, 0x48, 0xd2, 0x87, 0x31, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x38, 0x60, 0x7c, 0xa5, 0x42, 0x2e, 0x0e, 0x67, 0x28, 0x5b, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31,
	0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0xd2, 0xe1, 0x12, 0xca, 0xc8,
	0x4c, 0xcf, 0x48, 0x2d, 0x2e, 0x89, 0x2f, 0x28, 0xca, 0x4c, 0x4e, 0x8d, 0x4f, 0x49, 0x2c, 0x49,
	0x95, 0x60, 0x02, 0xab, 0x10, 0x80, 0xca, 0x04, 0x80, 0x24, 0x5c, 0x12, 0x4b, 0x52, 0x85, 0x94,
	0xb9, 0x78, 0x51, 0x54, 0x4b, 0x30, 0x83, 0x15, 0xf2, 0x20, 0x2b, 0x74, 0xe2, 0x89, 0xe2, 0x42,
	0xb8, 0x2c, 0x89, 0x0d, 0xec, 0x22, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xfa, 0xe8,
	0x86, 0xae, 0x00, 0x00, 0x00,
}
